// Mirrors the fixed amenities dictionary rendered on the public site
// (frontend/src/components/AmenitiesList.jsx). Kept as a separate backend
// copy so HostPanel/WoNoMasterPanel can fetch it without depending on the
// public frontend bundle — update both places together if the list changes.
export const fixedAmenitiesMap = {
  coworking: [
    "Private Desk",
    "Private Storage",
    "Air Conditioning",
    "High Speed Wi-Fi",
    "Wi-Fi",
    "IT Support",
    "Tea & Coffee",
    "Reception Support",
    "Admin Support",
    "Housekeeping",
    "Community",
    "Maintenance",
    "Power Backup",
    "Meeting Room",
    "Cafeteria",
    "Printing Services",
    "CCTV Secure",
    "Purified Water",
    "Custom Solutions",
  ],
  coliving: [
    "Shared Space",
    "Private Space",
    "Private Storage",
    "Air Conditioning",
    "Wi-Fi",
    "High Speed Wi-Fi",
    "IT Support",
    "Tea & Coffee",
    "Reception Support",
    "Admin Support",
    "Housekeeping",
    "Community",
    "Maintenance",
    "Power Backup",
    "Cafeteria",
    "Printing Services",
    "Laundry Facilities",
    "CCTV Secure",
    "Swimming Pool",
  ],
  workation: [
    "Shared Space",
    "Private Space",
    "Private Storage",
    "Air Conditioning",
    "Wi-Fi",
    "High Speed Wi-Fi",
    "IT Support",
    "Tea & Coffee",
    "Reception Support",
    "Admin Support",
    "Housekeeping",
    "Community",
    "Maintenance",
    "Power Backup",
    "Cafeteria",
    "Printing Services",
    "Laundry Facilities",
    "CCTV Secure",
    "Swimming Pool",
  ],
  privatestay: [
    "Private Space",
    "Private Storage",
    "Television",
    "Air Conditioning",
    "Wi-Fi",
    "High Speed Wi-Fi",
    "IT Support",
    "Tea & Coffee",
    "Reception Support",
    "Admin Support",
    "Housekeeping",
    "Community",
    "Maintenance",
    "Power Backup",
    "Cafeteria",
    "Printing Services",
    "Washing Machine",
    "CCTV Secure",
    "Swimming Pool",
  ],
  hostel: [
    "Shared Space",
    "Private Space",
    "Private Storage",
    "Air Conditioning",
    "Wi-Fi",
    "High Speed Wi-Fi",
    "IT Support",
    "Tea & Coffee",
    "Reception Support",
    "Admin Support",
    "Housekeeping",
    "Community",
    "Maintenance",
    "Power Backup",
    "Cafeteria",
    "Printing Services",
    "Laundry Facilities",
    "CCTV Secure",
    "Swimming Pool",
  ],
  cafe: [
    "Private Desk",
    "Private Storage",
    "Air Conditioning",
    "High Speed Wi-Fi",
    "Wi-Fi",
    "IT Support",
    "Tea & Coffee",
    "Reception Support",
    "Admin Support",
    "Housekeeping",
    "Community",
    "Maintenance",
    "Power Backup",
    "Visitor allowed",
    "Cafeteria",
    "Printing Services",
    "CCTV Secure",
    "Water Purifier",
    "Custom Solutions",
  ],
  meetingroom: [
    "Private Meeting Room",
    "Smart Television",
    "Air Conditioning",
    "High Speed Wi-Fi",
    "Wi-Fi",
    "IT Support",
    "Tea & Coffee",
    "Reception Support",
    "Admin Support",
    "Housekeeping",
    "Community",
    "Maintenance",
    "Power Backup",
    "Visitor allowed",
    "Cafeteria",
    "Printing Services",
    "CCTV Secure",
    "Water Purifier",
    "Custom Solutions",
  ],
};

export default fixedAmenitiesMap;
