const sharedImages = [
  "/images/goa-image.jpg",
  "/images/bali-image.jpg",
  "/images/bangkok-image.jpg",
  "/images/dubai-image.webp",
  "/images/budapest-image.jpg",
  "/images/auckland-image.jpg",
];

const destinations = [
  ["Lisbon", "Portugal", "Europe"],
  ["Dubai", "UAE", "Asia"],
  ["Barcelona", "Spain", "Europe"],
  ["Bali", "Indonesia", "Asia"],
  ["Bangkok", "Thailand", "Asia"],
  ["Prague", "Czech Republic", "Europe"],
  ["Kuala Lumpur", "Malaysia", "Asia"],
  ["Mexico City", "Mexico", "North America"],
  ["Medellín", "Colombia", "South America"],
  ["Porto", "Portugal", "Europe"],
  ["Valencia", "Spain", "Europe"],
  ["Budapest", "Hungary", "Europe"],
  ["Chiang Mai", "Thailand", "Asia"],
  ["Da Nang", "Vietnam", "Asia"],
  ["Tbilisi", "Georgia", "Europe"],
  ["Phuket", "Thailand", "Asia"],
  ["Penang", "Malaysia", "Asia"],
  ["Canary Islands", "Spain", "Europe"],
  ["Goa", "India", "Asia"],
  ["Tallinn", "Estonia", "Europe"],
  ["Montreal", "Canada", "North America"],
  ["Vancouver", "Canada", "North America"],
  ["Toronto", "Canada", "North America"],
  ["Austin", "USA", "North America"],
  ["Miami", "USA", "North America"],
  ["Istanbul", "Turkey", "Europe"],
  ["Athens", "Greece", "Europe"],
  ["Kraków", "Poland", "Europe"],
  ["Buenos Aires", "Argentina", "South America"],
  ["Santiago", "Chile", "South America"],
  ["Ho Chi Minh City", "Vietnam", "Asia"],
  ["Hanoi", "Vietnam", "Asia"],
  ["Bucharest", "Romania", "Europe"],
  ["Sofia", "Bulgaria", "Europe"],
  ["Belgrade", "Serbia", "Europe"],
  ["Quito", "Ecuador", "South America"],
  ["Montevideo", "Uruguay", "South America"],
  ["Nairobi", "Kenya", "Africa"],
  ["Kigali", "Rwanda", "Africa"],
  ["Cebu City", "Philippines", "Asia"],
  ["Yogyakarta", "Indonesia", "Asia"],
  ["Bologna", "Italy", "Europe"],
  ["Santa Catarina", "Brazil", "South America"],
  ["Quintana Roo", "Mexico", "North America"],
  ["Western Cape", "South Africa", "Africa"],
  ["Gold Coast", "Australia", "Oceania"],
  ["Auckland", "New Zealand", "Oceania"],
  ["North Holland", "Netherlands", "Europe"],
  ["San José Province", "Costa Rica", "South America"],
  ["Santa Cruz de Tenerife", "Spain", "Europe"],
  ["Funchal", "Portugal", "Europe"],
  ["Tulum", "Mexico", "North America"],
  ["Bogota", "Colombia", "South America"],
  ["Lima", "Peru", "South America"],
  ["Colombo", "Sri Lanka", "Asia"],
  ["Marrakech", "Morocco", "Africa"],
  ["Casablanca-Settat", "Morocco", "Africa"],
  ["Lagos (Portugal)", "Portugal", "Europe"],
  ["Koh Phangan", "Thailand", "Asia"],
  ["Cairo Governorate", "Egypt", "Africa"],
  ["Surigao del Norte", "Philippines", "Asia"],
  ["Nassau", "Bahamas", "North America"],
  ["Otago Region", "New Zealand", "Oceania"],
  ["Nadi", "Fiji", "Oceania"],
  ["Fes-Meknes", "Morocco", "Africa"],
  ["Sao Paulo", "Brazil", "South America"],
  ["Rio de Janeiro", "Brazil", "South America"],
  ["Manila", "Philippines", "Asia"],
  ["Cali", "Colombia", "South America"],
  ["Oaxaca", "Mexico", "North America"],
  ["Victoria", "Canada", "North America"],
  ["Pittsburgh", "USA", "North America"],
  ["Lagos State", "Nigeria", "Africa"],
  ["Abuja", "Nigeria", "Africa"],
  ["Giza Governorate", "Egypt", "Africa"],
];

export const aiDestinationCards = destinations.map(
  ([city, country, continent], index) => ({
    city,
    country,
    continent,
    suggestions: 102 - (index % 30),
    image: sharedImages[index % sharedImages.length],
  }),
);
