export const goalFilterMap = {
  "World Ranking": [
    "Best for Nomads",
    "Most Affordable",
    "Safest Cities",
    "Easy Visa / Long Stay",
    "Strong Nomad Community",
    "Healthcare Friendly",
    "Startup / Business Opportunities",
    "Clean Air / Environment",
    "Best Work Infrastructure",
  ],
  "Work From Anywhere": [
    "Best for Remote Work Setup",
    "Cheapest Places",
    "Best Connected Cities (Flights)",
    "Strong Nomad Community",
    "Fast Internet Cities",
    "Best Work Infrastructure",
  ],
  "Increase Your Savings": [
    "Maximum Savings",
    "Low Taxation",
    "Purchasing Power",
    "Financial Stability(Low Risk)",
    "Startup Setup Cost",
    "Balanced Financial Lifestyle",
  ],
  "Advance Your Career": [
    "Startup Ecosystems",
    "Remote Job Opportunities",
    "Founder Nomads",
    "Tech Talent Density",
    "Startup Incubators & Accelerators",
    "Balanced Career Growth",
    "Venture Capital Presence",
    "Conferences & Events",
  ],
  "Find Your Community": [
    "Social & Party Lifestyle",
    "Chill & Wellness Lifestyle",
    "Adventure & Exploration",
    "Nomad Community & Networking",
    "Couple - Friendly Lifestyle",
    "Family - Friendly Lifestyle",
    "Female Friendly Lifestyle",
    "Founder Nomads",
    "Solo Nomads",
  ],
};

export const defaultGoal = "Work From Anywhere";

const goalOptionBadgeLabelMap = {
  "Internet Speed Index": "Mbps",
  "Internet Speed": "Mbps",
  "Cost Of Living": "Dollars",
  "Healthcare Cost Index": "Index",
  "Healthcare Cost": "Index",
  "Overall Ranking Index": "Score",
  "Safety Ranking Index": "Score",
  "Nomad Population Index": "Score",
  "Air Quality Index": "AQI",
  "Visa Flexibility": "Score",
  "Startup Ecosystems (No Of Startups)": "Startups",
  "Remote Working Infrastructure": "Score",
  "Overall Work From Anywhere Index": "Score",
  "Digital Nomad Visas": "Countries",
  "Visa-Free Entry Length": "Days",
  "Visa On Arrival": "Countries",
  "Airport Connectivity": "Score",
  "Direct International Flights": "Routes",
  "Global Accessibility": "Score",
  "Overall Savings Index": "Score",
  "Lower Taxes (Company, Personal, Nomad)": "%",
  "Purchasing Power": "Index",
  "Inflation Stability": "Score",
  "Startup Setup Cost": "USD",
  "Overall For Career Index": "Score",
  "Venture Capital Presence": "Score",
  "Startup Incubators & Accelerators": "Hubs",
  "Tech Talent Density": "Index",
  "Conferences And Events": "Events",
  "Remote Job Availability": "Openings",
  "Founder Nomads": "Score",
  "Overall Compatibility Index": "Score",
  "Meetups And Events": "Events",
  "Solo Nomad Traveller": "Score",
  "Family Nomad Traveller": "Score",
  "Girl Nomad Traveller": "Score",
  "Couple Nomad Travellers": "Score",
  "Party & Events Nomad Traveller": "Score",
  "Founder Nomad Traveller": "Score",
  "Nature Nomad Travelling": "Score",
  "Adventure Nomad Travelling": "Score",
  "Nightlife & Pubs": "Score",
  Yoga: "Score",
  "Nomad Community Presence": "Score",
};

export const getGoalOptionMetricLabel = (goalOption) => {
  if (!goalOption) {
    return "Mbps";
  }

  return goalOptionBadgeLabelMap[goalOption] || "Score";
};
