export const goalFilterMap = {
  "World Ranking": [
    "Overall World Ranking Index",
    "Continentwise Ranking Index",
    "Safety World Ranking Index",
    "Nomad Population Index",
    "Healthcare Cost Index",
    "Air quality Index",
    "Visa Flexibility",
    "Cost of living (live, work, eat, travel etc)",
    "Internet Speed Index",
    "Startup ecosystems (No of startups)",
    "Remote working infrastructure",
  ],
  "Work From Anywhere": [
    "Overall Work from anywhere Index",
    "Digital nomad visas",
    "Visa-free entry length",
    "Visa On Arrival",
    "Airport connectivity",
    "Direct international flights",
    "Internet speed",
    "Global accessibility",
    "Cost of living (live, work, eat, travel etc)",
    "Nomad Population Index",
    "Remote working infrastructure",
  ],
  "Increase Your Savings": [
    "Overall Savings Index",
    "Cost of living (live, work, eat, travel etc)",
    "Lower taxes (company, personal, nomad)",
    "Purchasing Power (Currency advantage)",
    "Healthcare Cost",
    "Inflation Stability (Past 5 yrs, future, currency vol, cost growth rate)",
    "Startup setup cost",
  ],
  "Advance Your Career": [
    "Overall for Career Index",
    "Startup ecosystems (No of startups)",
    "Venture capital presence",
    "Startup incubators & Accelerators",
    "Tech talent density",
    "Conferences and events",
    "Remote job availability",
    "Founder Nomads",
  ],
  "Find Your Community": [
    "Overall Compatibility Index",
    "Meetups and events",
    "Solo Nomad Traveller",
    "Family Nomad Traveller",
    "Girl Nomad Traveller",
    "Couple Nomad Travellers",
    "Party & Events Nomad Traveller",
    "Founder Nomad Traveller",
    "Nature Nomad Travelling",
    "Adventure Nomad Travelling",
    "Nightlife & Pubs",
    "Yoga",
    "Nomad community presence",
  ],
};

export const defaultGoal = "Work From Anywhere";
